name: My Application

on:
 push:
  branches: [ master ]
 pull_request:
  branches: [ master ]


jobs:
 build:

   run-on: ubuntu:latest

   steps:
   - uses: actions/checkout@v1
   - name: Build & Push Image
   run:
    echo "Hi there i am building image"
    docker image build -t nikitamathur/MyApp:V1
