name: My Application

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Build & Push Image
      run: |
        echo "Hi there, I am building the image"
        docker build -t nikitamathur/myapp:V1 .

