name: My Application

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2


    - name: login to docker hub
      run: docker login -u ${{ secrets.Docker_Username }} -p ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build Image
      uses: docker/build-push-action@v2
      with:
       repository: nikitamathur/myapp
       tags: latest, ${{github.run_number}}
#      run: |
#        echo "Hi there, I am building the image"
#        docker build -t nikitamathur/myapp .
    
    - name: Push Docker Image to Hub
      run: docker push nikitamathur/myapp:latest, ${{github.run_number}}
    
      

      
