name: My Application

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Build
      run: |
        echo "Hi there, I am building the image"
        docker build -t nikitamathur/myapp:V1 .
    
    - name: Publish to docker hub
      uses: docker/build-push-action@v2
      with:
        username: ${{ secrets.Docker_Username }}
        password: ${{ secrets.DOCKER_PASSWORD}}
        repository: nikitamathur/myapp
        tags: latest, ${{github.run_number}}

      
