name: My Application

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2


    - name: login to docker hub
      run: docker login -u ${{ secrets.Docker_Username }} -p ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build Image
      run: docker build -t nikitamathur/myapp:version${{ github.run_number }} .
     
    - name: show images name
      run: |
         echo "Hi there, I am building the image"
         docker images
    
    - name: Push Docker Image to Hub
      run: docker push nikitamathur/myapp:version${{ github.run_number }}
    
      

      
